server:
  port: 8081

spring:

  application:
    name: activity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/activity_db
    username: admin
    password: admin

services:

  user:
    url: http://localhost:8081

  activity:
    url: http://localhost:8082

  dashboard:
    url: http://localhost:8083

  gateway:
    url: http://localhost:8080